### ISSUE TITLE
xml contain registration

### ISSUE THREAD

**Issue by tischi** [mobie/clem-example-project#12]
@martinschorb @constantinpape 
The xml seem to contain the registration, e.g. [here](https://github.com/mobie/clem-example-project/blob/2dec67346fbc57f29ce6f7d8e3bf02c20794b72e/data/hela/images/bdv-n5-s3/tomo_37_lm.xml#L41).
While I don't think this is forbidden, the current spec discourages this and prefers to only have the voxel scaling in the xml; while registrations should be specified in the dataset.json document.

As a consequence of putting registration into the xml I think the grid views produce surprising behavior:

<img width="684" alt="image" src="https://user-images.githubusercontent.com/2157566/136420820-cd50e7c5-cb56-4953-b75c-43d812a4ff35.png">

If you really want to keep the registration within the xml then you could try adding a `centerAtOrigin = true` to the view to make the grid view work. But this will probably not give you what you want for showing the hm and lm tomograms on top of each other in a grid.

I think we could be less ambitious here and just show two grids with the lm and hm tomograms alone.

**Comment by martinschorb** [comment]
> If you really want to keep the registration within the xml

The issue with EM sources exported from SerialEM is, that for internal mapping of microscope coordinates (stage, beam etc.), it generates an affine matrix that takes all scaling, rotations and even anisotropic stretching (when imaging a tilted sample) into account. This is the inital matrix that I extract and put into the XML (called `MapScaleMat`). This means I don't even have access to the scaling and other transformations separately.

**Comment by martinschorb** [comment]
The only thing that exists as separate information is the translation to the physical position. AFAIK this is what @constantinpape  did already separate out into the view.

**Comment by martinschorb** [comment]
> The only thing that exists as separate information is the translation to the physical position. AFAIK this is what @constantinpape did already separate out into the view.

I think that for a grid (of tomograms) it makes sense to leave the sources untouched and only scale them. If you look closely, the tomograms inside the CLEM dataset are not exatcly squared. This is because of that transform not being 100% isotropic. When only looking at them without context, they should only be scaled.

Is it possible to load a BDV-XML source and ignore the included transformation? The XML always have the ` <voxelSize>`
field properly filled with the nominal scaling values. One could just generate a scaling accordingly.
